projects/project-metadata.json
projects/project-version/159-spring-security-Versiondetails.json
projects/project-version/459-spring-data-jpa-Versiondetails.json
projects/project-version/460-spring-session-Versiondetails.json
projects/project-version/463-spring-data-mongodb-Versiondetails.json
projects/project-version/464-spring-data-redis-Versiondetails.json
projects/project-version/465-spring-kafka-Versiondetails.json
projects/project-version/85-spring-boot-Versiondetails.json

Added tracking details of spring-boot stack apps - total 7 apps

Spring-boot stack apps added

---

models/model-metadata.json

Change in model metadata for the Classic models

Change in model metadata for the Classic models

---

projects/project-metadata.json
projects/project-version/475-newrelic-java-agent-Versiondetails.json

added newrelic-java-agent to project of interest

newrelic-java-agent

---

projects/project-version/171-saleor-Versiondetails.json
projects/project-version/418-jackson-databind-Versiondetails.json

saleor https://github.com/Be-Secure/Be-Secure/issues/171
jackson-databind https://github.com/Be-Secure/Be-Secure/issues/418

correcting saleor version number

---

projects/project-metadata.json
projects/project-version/461-watchtower-Versiondetails.json

https://github.com/Be-Secure/Be-Secure/issues/461

Added watchtower

---

projects/project-version/461-watchtower-Versiondetails.json

https://github.com/Be-Secure/Be-Secure/issues/461

Updated criticality_score 

---

projects/project-version/252-rosdistro-Versiondetails.json

rosdistro https://github.com/Be-Secure/Be-Secure/issues/252

renaming rodistro version

---

projects/project-version/235-logstash-Versiondetails.json
projects/project-version/299-prometheus-Versiondetails.json
projects/project-version/453-kubernetes-Versiondetails.json
projects/project-version/471-radius-Versiondetails.json
projects/project-version/472-opentofu-Versiondetails.json
projects/project-version/80-ort-Versiondetails.json

logstash: https://github.com/Be-Secure/Be-Secure/issues/235
prometheus: https://github.com/Be-Secure/Be-Secure/issues/299
kubernetes: https://github.com/Be-Secure/Be-Secure/issues/453
radius: https://github.com/Be-Secure/Be-Secure/issues/471
opentofu: https://github.com/Be-Secure/Be-Secure/issues/472
ort: https://github.com/Be-Secure/Be-Secure/issues/80

updating versiondetails

---

projects/project-version/259-mythril-Versiondetails.json
projects/project-version/453-kubernetes-Versiondetails.json
projects/project-version/469-viagrunts-Versiondetails.json
projects/project-version/470-langchain-Versiondetails.json
projects/project-version/471-radius-Versiondetails.json

mythril: https://github.com/Be-Secure/Be-Secure/issues/259
kubernetes: https://github.com/Be-Secure/Be-Secure/issues/453
radius: https://github.com/Be-Secure/Be-Secure/issues/471
viagrunts: https://github.com/Be-Secure/Be-Secure/issues/469
langchain: https://github.com/Be-Secure/Be-Secure/issues/470

updating missing reports

---

projects/project-metadata.json

"bes_technology_stack" for security-analytics-export-tools, opstrace , codeclimate, dvc, mlem, terraform-provider-luminate from S to DO

"bes_technology_stack" for security-analytics-export-tools, opstrace , codeclimate, dvc, mlem, terraform-provider-luminate from S to DO

---

projects/project-version/495-stride-gpt-Versiondetails.json
projects/project-version/496-aicert-Versiondetails.json
projects/project-version/497-blindai-Versiondetails.json

Updated scorecard & criticality_score in version details for clomonitor, blindai, stride-gpt and aicert.
https://github.com/Be-Secure/Be-Secure/issues/495
https://github.com/Be-Secure/Be-Secure/issues/496
https://github.com/Be-Secure/Be-Secure/issues/497
https://github.com/Be-Secure/Be-Secure/issues/498

Updated scorecard & criticality_score in version details

---

projects/project-metadata.json
projects/project-version/494-kedro-Versiondetails.json

https://github.com/Be-Secure/Be-Secure/issues/494

Added kedro metadata and verion details

---

projects/project-metadata.json
projects/project-version/253-openemr-Versiondetails.json
projects/project-version/505-minio-Versiondetails.json
projects/project-version/506-koalas-Versiondetails.json
projects/project-version/507-NNEF-Tools-Versiondetails.json
projects/project-version/508-spinnaker-Versiondetails.json
projects/project-version/509-openelb-Versiondetails.json
projects/project-version/510-openstack-Versiondetails.json

#minio
#koalas
#NNEF-Tools
#spinnaker
#openemr
#openelb
#openstack

Uploading Version Details and Project Metadata

---

projects/project-version/461-watchtower-Versiondetails.json

https://github.com/Be-Secure/Be-Secure/issues/461
Updated version details for watchtower v1.0.0

Added version details for watchtower v1.0.0

---

projects/project-metadata.json
projects/project-version/521-chainloop-Versiondetails.json

chainloop: https://github.com/Be-Secure/Be-Secure/issues/521

adding metadata for chainloop

---

projects/project-metadata.json
projects/project-version/531-PyRIT-Versiondetails.json

https://github.com/Be-Secure/Be-Secure/issues/531

Added PyRIT

---

projects/project-metadata.json

https://github.com/Be-Secure/Be-Secure/issues/531

Update: added compatible_environments in PyRIT metadata

---

projects/project-metadata.json
projects/project-version/526-gots-Versiondetails.json
projects/project-version/527-Porrtal-Versiondetails.json

prometheus: https://github.com/Be-Secure/Be-Secure/issues/299
logstash: https://github.com/Be-Secure/Be-Secure/issues/235
privacyidea: https://github.com/Be-Secure/Be-Secure/issues/377
gots: https://github.com/Be-Secure/Be-Secure/issues/526
Porrtal: https://github.com/Be-Secure/Be-Secure/issues/527

adding env data in project-metadata.json

---

projects/project-metadata.json
projects/project-version/340-gitleaks-Versiondetails.json
projects/project-version/504-kestra-Versiondetails.json
projects/project-version/542-apollo-Versiondetails.json
projects/project-version/543-openauto-Versiondetails.json
projects/project-version/544-oscc-Versiondetails.json
projects/project-version/545-night-vision-Versiondetails.json
projects/project-version/545-nightvision-Versiondetails.json

apollo: https://github.com/Be-Secure/Be-Secure/issues/542
openauto: https://github.com/Be-Secure/Be-Secure/issues/543
oscc: https://github.com/Be-Secure/Be-Secure/issues/544
night-vision: https://github.com/Be-Secure/Be-Secure/issues/545
kestra: https://github.com/Be-Secure/Be-Secure/issues/504
gitleaks: https://github.com/Be-Secure/Be-Secure/issues/340

apollo, openauto, osscc, night-vision metadata

---

projects/project-metadata.json
projects/project-version/125-cosign-Versiondetails.json
projects/project-version/126-grype-Versiondetails.json
projects/project-version/162-nmap-Versiondetails.json
projects/project-version/179-trivy-Versiondetails.json
projects/project-version/183-clair-Versiondetails.json
projects/project-version/185-threat-dragon-Versiondetails.json
projects/project-version/221-kyverno-Versiondetails.json
projects/project-version/275-zaproxy-Versiondetails.json
projects/project-version/276-DependencyCheck-Versiondetails.json
projects/project-version/334-sonarqube-Versiondetails.json
projects/project-version/337-sqlmap-Versiondetails.json
projects/project-version/361-bandit-Versiondetails.json
projects/project-version/553-fossology-Versiondetails.json
projects/project-version/554-oss-fuzz-Versiondetails.json

grype: https://github.com/Be-Secure/Be-Secure/issues/126
nmap: https://github.com/Be-Secure/Be-Secure/issues/162
trivy: https://github.com/Be-Secure/Be-Secure/issues/179
clair: https://github.com/Be-Secure/Be-Secure/issues/183
threat-dragon: https://github.com/Be-Secure/Be-Secure/issues/185
kyverno: https://github.com/Be-Secure/Be-Secure/issues/221
zaproxy: https://github.com/Be-Secure/Be-Secure/issues/275
DependencyCheck: https://github.com/Be-Secure/Be-Secure/issues/276
sonarqube: https://github.com/Be-Secure/Be-Secure/issues/334
sqlmap: https://github.com/Be-Secure/Be-Secure/issues/337
bandit: https://github.com/Be-Secure/Be-Secure/issues/361
fossology: https://github.com/Be-Secure/Be-Secure/issues/553
oss-fuzz: https://github.com/Be-Secure/Be-Secure/issues/554
cosign: …

adding metadata and version details

---

models/model-metadata.json

Onboarded llama3:8b model in BeSecure

Onboarded llama3:8b model

---

models/model-metadata.json

llama3.1:8b onboarded in BeSecure

llama3.1:8b onboarded in BeSecure

---

models/model-metadata.json

codellama and granite3.2 model metadata change

codellama and granite3.2 model metadata change

---

models/model-metadata.json

granite-code:8b name correction

granite-code:8b name correction
